server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Todas las rutas en una SPA deben redirigir al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché agresiva para recursos estáticos (imágenes, CSS, JS)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Denegar acceso a archivos ocultos (por seguridad)
    location ~ /\. {
        deny all;
    }
}
